[package]
name = "my-macro"
version = "0.1.0"
authors = ["chenwei <chenwei767@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#paste = "1.0"
